### ISSUE TITLE
pull artifact with file in parent path fails with Error: path_traversal_disallowed

### ISSUE THREAD

**Issue by yuwaMSFT2** [shizhMSFT/oras#37]
This should be the limit on tar. 
push is fine:
 sudo oras push yuwatestroles.azurecr.io/testoras:bash3 ../testbash

pull is not:
 sudo oras pull yuwatestroles.azurecr.io/testoras:bash3

should block on push?

**Comment by shizhMSFT** [comment]
Disallowing path traversal is for security considerations for content consumers. Meanwhile, we do not have restriction on the content providers.

To insecurely pull the content, you can do
```
oras pull -T yuwatestroles.azurecr.io/testoras:bash3
```
where `-T` means `--allow-path-traversal`.

BTW, you don't need `sudo` to run `oras`.

**Comment by yuwaMSFT2** [comment]
Ah I didn't see the option. Thanks.
